fix: add document click listener only in capture phase
antvis/X6 pull request #1205
Opened 2021-07-26 08:50 UTC by fengzilong

### Description

menubar 组件存在 bug，鼠标点击 menubar.item 后 menu 不会出现

### Motivation and Context

由于事件先捕获，后冒泡，导致 menubar/menubar.item active 之后立即去给 document 绑定 click 事件，document 会在冒泡阶段触发 listener 函数

这个 PR 修改了 document click listener 仅在捕获阶段触发来解决这个问题

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-28 10:04 UTC, NewByVector commented
我在官网不能重现你的问题（点击 File 的时候会出现下面的 menu）
![image](https://user-images.githubusercontent.com/20186737/127304229-957a47a9-a8be-4a0c-81f2-4c023ded8235.png)
是需要什么其他步骤吗？

2021-07-29 07:02 UTC, fengzilong commented
> 我在官网不能重现你的问题（点击 File 的时候会出现下面的 menu）
> ![image](https://user-images.githubusercontent.com/20186737/127304229-957a47a9-a8be-4a0c-81f2-4c023ded8235.png)
> 是需要什么其他步骤吗？

https://codesandbox.io/s/04qm5?file=/src/app.tsx:0-3943

你们官网的例子没问题，但是本地工程真正使用的时候就有问题了

在本地新建一个 react 工程，使用链接中 app.tsx 的代码就可以复现

2021-08-02 11:04 UTC, NewByVector commented
我在本地启动的 react 项目：

"@antv/x6-react-components": "^1.1.13",
"antd": "^4.16.1",
"react": "16.14.0",
"react-dom": "16.14.0"

![image](https://user-images.githubusercontent.com/20186737/127851788-3d6a578f-2ff7-4e23-b0ed-bcf7e54252f5.png)

是 OK 的，检查一下是不是本地哪些东西影响了

2021-08-06 01:30 UTC, NewByVector requested changes
需要你这边检查一下是不是自己环境导致的。

2021-08-16 02:00 UTC, closed without merging