feat: support shift key multi-selection
antvis/X6 pull request #2302
Opened 2022-07-02 10:59 UTC by MrMengJ

Closes: #2248

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-05 13:04 UTC, NewByVector requested changes

2022-07-05 13:04 UTC, NewByVector commented on packages/x6/src/graph/selection.ts
> +        (!e.ctrlKey && !e.metaKey && !e.shiftKey)
支持 shiftKey 增加一个配置吧，不然是 break change

2022-07-08 07:08 UTC, NewByVector commented
@MrMengJ 能否留个联系方式，方便交流。🧐

2022-07-08 07:13 UTC, MrMengJ commented
> @MrMengJ 能否留个联系方式，方便交流。🧐

微信 mengjin1227，最近太忙，一直在忙工作上的事情，本来打算周末抽个时间再提下PR的

2022-07-10 05:21 UTC, NewByVector approved these changes

2022-07-10 05:21 UTC, merged