feat: ✨ support scroller resize direction
antvis/X6 pull request #2408
Opened 2022-07-23 15:38 UTC by MrMengJ

Closes: #2323

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-17 14:48 UTC, NewByVector requested changes

2022-08-17 14:48 UTC, NewByVector commented on packages/x6/src/addon/scroller/index.ts
> +    let resizeOptions =
这里的 resizeOptions 在 390 行已经计算过一次，直接作为 calcContextArea 的参数传过来就行。

2022-08-17 14:49 UTC, NewByVector requested changes
409 行的 resizeOptions 在 390 行已经计算过一次，直接作为 calcContextArea 的参数传过来就行。

2022-08-25 13:46 UTC, NewByVector approved these changes

2022-08-25 13:46 UTC, merged

2022-09-19 09:22 UTC, OpportunityLiu commented on packages/x6/src/addon/scroller/index.ts
> +          direction: AutoResizeDirection | AutoResizeDirection[]
这里没有设为可选，导致以前的代码编译不过了。。

2022-09-26 10:54 UTC, OpportunityLiu commented on packages/x6/src/addon/scroller/index.ts
> +      return this.graph.transform.getContentArea()
今天又发现一个问题，这里没有把 `resizeOptions` 传进去，导致我在 `autoResizeOptions` 给的 `useCellGeometry: true` 不起作用

2022-09-26 10:59 UTC, OpportunityLiu commented on packages/x6/src/addon/scroller/index.ts
> +    function getCellBBox(cell: Cell) {
这些实现好像又默认 `useCellGeometry: true` 了，没使用 `Dom.getBBox` 之类的 API