fix: 升级vue-demi版本
antvis/X6 pull request #2435
Opened 2022-07-28 08:52 UTC by lijing666

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-28 13:40 UTC, NewByVector requested changes

2022-07-28 13:40 UTC, NewByVector commented on packages/x6-vue-shape/package.json
> +    "vue-demi": "latest"
直接用 latest 不好吧，万一有 break change 呢？

2022-07-29 01:04 UTC, lijing666 commented on packages/x6-vue-shape/package.json
> +    "vue-demi": "latest"
vue-demi一般推荐用latest，因为它就是个适配器，如果你不及时更新，很可能就出现不兼容各个vue版本或者有某些隐藏的问题无法修复，因为是适配器，使用的时候也应该注意，不要使用deprecated的api即可保证

2022-07-29 01:09 UTC, lijing666 commented on packages/x6-vue-shape/package.json
> +    "vue-demi": "latest"
本来这个@antv/x6-vue-shape包里还有一些ts中使用namespace的过时语法，我也重构了，但是无法提交代码，这个包lint时依赖@antv/eslint-config你们好像是没有发布的，不知道怎么搞，后续2.0分开各个模块后，希望能以比较友好的方式提供给贡献者

2022-08-01 01:38 UTC, lijing666 commented
@NewByVector 还有一个原因使用vue-demi的latest版本，因为别的库都使用的latest，但是antv却使用了较低版本，就会出现依赖过个vue-demi的版本问题；大概什么时候可以发布一个x6-vue-shape的包呢，现在升级到了vue2.7，这个x6-vue-shape不升级项目跑不起来了，谢谢

2022-08-01 21:36 UTC, NewByVector commented
@lijing666 我今天发布一个新的版本。

2022-08-01 21:36 UTC, NewByVector approved these changes

2022-08-01 21:36 UTC, merged

2022-08-02 00:59 UTC, lijing666 commented
> @lijing666 我今天发布一个新的版本。

你早上五六点就上班了，辛苦了，谢谢

2022-08-08 08:50 UTC, NewByVector commented
不好意思，后面忙忘了， 更新到 1.4.2 版本就好了。

2022-08-09 08:35 UTC, lijing666 commented
> 不好意思，后面忙忘了， 更新到 1.4.2 版本就好了。

没事，谢谢了

2022-08-09 08:35 UTC, lijing666 commented
> 不好意思，后面忙忘了， 更新到 1.4.2 版本就好了。

没事，谢谢了