feat: ✨ HTML Shape支持配置mount+unmount生命周期回调 #2524
antvis/X6 pull request #2529
Opened 2022-08-16 10:26 UTC by lloydzhou

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [x] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-16 10:38 UTC, lloydzhou commented
使用纯html和react分别定义了一个带交互和数据扭转的组件，用mount+unmount的方式挂载到HTML节点内部
```
    // 增加一个原生html的组件
    const target1 = graph.addNode({
      x: 280,
      y: 100,
      width: 100,
      height: 40,
      shape: 'html',
      html: {
        mount: async (props: any) => {
          console.log('mount', props)
          const { node } = props
          // 生成新的节点
          const wrap1 = wrap.cloneNode()
          wrap1.innerText = '+'
          // 监听data变化
          node.on('change:data', () => {
            wrap1.innerText = node.getData().num
          })
          // 增加交互，点击后更新data
          wrap1.addEventListener(
            'click',
            () => {
              const { num = 0 } = node.getData() || {}
              console.log('inc num', num)
              node.setData({ num: num + 1 })
            },
            false,
          )
          // 这里可以直接添加到container或者返回后由x6内置的view添加到container内部
          // props.container.appendChild(wrap1)
          return wrap1
        },
        unmount: async (props: any) => {
          console.log('unmount', props)
        },
      },
    })
    console.log('target1', target1)

    // 使用react定义一个组件
    const TestComponent = (props) => {
      const { node } = props
      const [num, setNum] = useState(0)
      node.on('change:data', () => {
        setNum(node.getData().num)
      })
      const inc = useCallback(() => {
        node.setData({ num: num + 1 })
      }, [num])
      return (
        <Button size="small" onClick={inc}>
          Antd Button {num}
        </Button>
      )
    }
    // 使用html的模式渲染react组件
    const target2 = graph.addNode({
      x: 480,
      y: 100,
      width: 100,
      height: 40,
      shape: 'html',
      html: {
        mount: async (props: any) => {
          // 挂载自定义组件到节点内部
          ReactDOM.render(<TestComponent {...props} />, props.container)
        },
        unmount: async (props: any) => {
          console.log('unmount', props)
        },
      },
    })
```
![image](https://user-images.githubusercontent.com/1826685/184859438-552f2f25-9756-4742-9591-4378b3f86f22.png)

2022-08-16 12:06 UTC, lloydzhou commented on sites/x6-sites-demos/packages/tutorial/advanced/react/html-shape/src/app.tsx
> +          console.log('unmount', props)
这里需要主动调用`ReactDOM.unmountComponentAtNode`

2022-08-17 03:05 UTC, lloydzhou commented
# ReactPortal demo

```
const useProtal = (() => {
  let instance: any = {}
  return function() {
    // 使用单例模式
    if (instance.Portal) {
      return instance
    }
    // 在作用域内生成一个挂载所有portal的容器
    const Portal = () => {
      const [items, setItems] = React.useState<{id: string, portal: React.ReactPortal}[]>([])
      instance.connect = React.useCallback((id: string, portal: React.ReactPortal) => {
        setItems([...items, {id, portal}])
      }, [items])
      instance.disconnect = React.useCallback((id: string) => {
        setItems(items.filter(i => i.id !== id))
      }, [items])
      return (<>{items.map(item => item.portal)}</>)
    }
    instance.Portal = Portal
    // 向外暴露一个wrap方法，这个方法自动处理mount和umount逻辑（创建ReactPortal并挂载到节点内部）
    instance.wrap = (Component: any) => ({
      mount: async (props: any) => {
        const { graph, node, container } = props
        // 这里使用graph.view.id做前缀
        const id = `${graph.view.id}:${node.view.id}`
        instance.connect(id, ReactDOM.createPortal(<Component {...props} />, container))
      },
      unmount: async (props: any) => {
        const { graph, node } = props
        const id = `${graph.view.id}:${node.view.id}`
        instance.disconnect(id)
      }
    })
    return instance
  }
})();

const portal = useProtal()
const { Portal } = portal

export default class Example extends React.Component {
  componentDidMount() {
    // .....
    const target3 = graph.addNode({
      x: 680,
      y: 100,
      width: 100,
      height: 40,
      shape: 'html',
      // wrap方法内部会自动createPortal并且挂载到节点的foContent上面
      html: portal.wrap(TestComponent),
    })
  }
  render() {
    return (
      <div className="app">
        <div className="app-content" ref={this.refContainer} />
        <!-- 全局挂载一下Portal中间注册的节点会自动渲染到节点内部 -->
        <Portal />
      </div>
    )
  }
}
```

2022-08-17 16:02 UTC, lloydzhou commented
> 我想了一下，现在这种形式写增加了使用者的负担，和之前的写法相比，效果并不明显，还没有足够能打动的地方。如果想精确控制组件加载、卸载、更新，完全可以继承 react-shape/vue-shape,重新定义一些方法。

1. 或许我太急于去证明可以使用这种方式去集成react/vue之类的
2. 其实添加`mount`+`unmount`最大的改变在于，把`shouldUpdate`这样的逻辑交给用户。
> 其实我观察了一下当前系统提供`shouldUpdate`应该很少人去使用
> 主要是这里存在一个问题，一般用户自己注册进来的组件会有自己的一套`effect`的逻辑，我们在外层再去判断`shouldUpdate`应该不能影响到自定义组件内部
> 除非我们认为用户注册进来的仅仅是一个`template`，一个简单的模板引擎
4. 并且主动调用`unmount`也能避免 （#2534） 这样的问题
5. 另外，我其实对现在的实现也不太满意（我应该新增加一个函数在init里面去调用`mount`，而不是现在这样和之前的renderHTMLComponent揉到一起）

2022-08-17 16:12 UTC, lloydzhou commented
> 如果想精确控制组件加载、卸载、更新，完全可以继承 react-shape/vue-shape,重新定义一些方法。

这里参照`single-spa`的接口，只使用了其中的`mount`+`unmount`，这样抽象带来的好处不仅限于这两个框架。

例如demo里面通过监听`change:data`使用原生的javascript的语法也能实现一个带有`effect`作用的组件

2022-08-25 13:59 UTC, NewByVector requested changes
这个方案还需要继续考虑一些，我的一些观点：

1. 并没有降低使用复杂度，反而在某些地方增加了一些使用门槛（比如让用户自己使用 ReactDom.render）
2. 组件的更新让用户自己维护其实也是一个负担，最好是我们自己做掉。因为大部分场景，都是 node data 改变后刷新 component

2022-08-25 15:46 UTC, lloydzhou commented
> 1. 并没有降低使用复杂度，反而在某些地方增加了一些使用门槛（比如让用户自己使用 ReactDom.render）

这个PR核心的其实是`HTML Shape`增加支持配置`mount`+`unmount`生命周期钩子。
所以我移除了提交里面一些无关的东西。
增加这一个新的配置方式，其本质的目的并不是为了替换`x6-react-shape`之类的功能。

> 2. 组件的更新让用户自己维护其实也是一个负担，最好是我们自己做掉。因为大部分场景，都是 node data 改变后刷新 component

这一点，我也比较赞成。我看现在的`x6-react-shape`里面实现的Wrap组件就自动监听`change:*`触发组件重新渲染。
不过这个PR只是提供了一种新的集成`HTML Shape`的方式。既然内部是html，那用户自己去维护数据更新也比较正常。

2022-11-05 12:33 UTC, closed without merging