fix: 🐛 #2581 修复 scheduler 任务调度的问题 (#2581)
antvis/X6 pull request #2582
Opened 2022-08-26 01:43 UTC by AricZhu

### Description

### Motivation and Context

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-28 13:08 UTC, NewByVector requested changes

2022-08-28 13:08 UTC, NewByVector commented on packages/x6/src/util/scheduler/index.ts
> +    const cb = () => unit.splice(0, unit.length)[0]?.()
直接使用 unit.splice(0, 1).forEach((c) => c()) 比较好。

2022-08-29 02:29 UTC, AricZhu commented on packages/x6/src/util/scheduler/index.ts
> +    const cb = () => unit.splice(0, unit.length)[0]?.()
这里不清空 unit 队列的话会有 bug，会导致任务超时被挂起后，后续就再也不会被触发了（schedule 中由于 unit 没有被清空，所以永远满足不了 length 为 1 的条件，后续的 postMessage 也就不会被调用）

2022-08-29 09:13 UTC, NewByVector approved these changes

2022-08-29 09:13 UTC, merged