feat: ✨ dnd support dndContainer
antvis/X6 pull request #2585
Opened 2022-08-26 06:34 UTC by lloydzhou

### Description
close #2562 #2572

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-28 13:19 UTC, NewByVector requested changes

2022-08-28 13:19 UTC, NewByVector commented on packages/x6/src/addon/dnd/index.ts
> +    dndContainer?: HTMLElement
传 html node，会有一个问题，不同样式会导致计算出的 area 不一致，后面可能会出现很多这样的 issue。这里改成传 dnd 区域的 react (x, y, width, height) 是否更合理？

2022-08-28 13:58 UTC, lloydzhou commented on packages/x6/src/addon/dnd/index.ts
> +    dndContainer?: HTMLElement
> 传 html node，会有一个问题，不同样式会导致计算出的 area 不一致，后面可能会出现很多这样的 issue。这里改成传 dnd 区域的 react (x, y, width, height) 是否更合理？

使用Dnd大致的步骤是：
1. 初始化Dnd
2. 写一个startDrag回调函数，这个函数里面调用`dnd.start(node, e)`
3. 渲染dnd工具箱（实际的场景，这里通常都是动态数据）。给每一个节点绑定`startDrag`回调

这里如果要求在初始化Dnd的时候传入`react (x, y, width, height)`可能是不合理的，
如果上面第三步的渲染工具箱是一个异步的过程，就可能导致这个工具箱内部的数据渲染完成之前，都没法计算出实际的区域，从而导致没法正确的使用`react (x, y, width, height)`初始化Dnd对象

2022-08-29 09:15 UTC, NewByVector commented on packages/x6/src/addon/dnd/index.ts
> +    dndContainer?: HTMLElement
这个区域其实是 dnd 容器的区域，这个区域事先应该是知道的吧。

2022-08-31 14:33 UTC, lloydzhou commented on packages/x6/src/addon/dnd/index.ts
> +    dndContainer?: HTMLElement
我这里有一个这样的场景：
1. 所有的组件是分组收起来的，收起来的方式类似ant design的侧边栏菜单，收起来的时候是一整个图标
![image](https://user-images.githubusercontent.com/1826685/187702106-c203ac7a-34d2-4aeb-b509-51bb1cf13ffd.png)

2. 分组下的可拖拽的图标是悬浮在画布上面的，对于这样的场景，传递rect区域明显是不合适的，但是传递dndContainer是可以的（只要确保悬浮的子菜单是渲染在同一个div下面即可）
![image](https://user-images.githubusercontent.com/1826685/187700145-68162717-7a5f-40dd-b606-9c461189e29b.png)

3. 另外，我看了内部获取真实的area的函数，使用了jquery的offset，我相信这个函数本身应该已经处理了很多的兼容性问题，像你提到的计算area不一致的情况应该很少会出现
4. 所有我的意见是，不想因为这种很少出现的问题而舍弃一个简单的配置，换成一个复杂的配置。

2022-09-12 09:17 UTC, NewByVector approved these changes

2022-09-12 09:17 UTC, merged