Feat plugins dis and en
antvis/X6 pull request #3171
Opened 2023-01-28 07:52 UTC by struggleRoue

### Description
https://github.com/antvis/X6/issues/3142
增加disable和enable能力

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-01-28 07:55 UTC, NewByVector requested changes

2023-01-28 07:55 UTC, NewByVector commented on packages/x6/src/graph/graph.ts
> +    disable: () => void
这里的类型可以先写为 ?: ,因为现在有很多插件没有实现 enable 和 disable 方法。

2023-01-28 08:00 UTC, struggleRoue commented on packages/x6/src/graph/graph.ts
> +    disable: () => void
可以 那我先兼容一下

2023-01-29 02:02 UTC, NewByVector requested changes

2023-01-29 02:02 UTC, NewByVector commented on packages/x6/src/graph/graph.ts
> +    disable?: () => void
这里返回值类型也需要推敲一下，例如 selection 插件中，enable 方法返回值是 this，感觉可以统一一下。

2023-01-29 02:59 UTC, struggleRoue commented on packages/x6/src/graph/graph.ts
> +    disable?: () => void
你觉得统一成什么比较好？
我一般理解disable和enable不会返回this，我理解void好一点

2023-02-02 03:06 UTC, NewByVector requested changes

2023-02-02 10:05 UTC, NewByVector requested changes

2023-02-02 10:05 UTC, NewByVector commented on packages/x6/src/graph/graph.ts
> +      plugin?.dispose?.()
plugin?.dispose?.()   =>  plugin.dispose()

2023-02-03 06:09 UTC, NewByVector approved these changes

2023-02-03 06:10 UTC, merged