feat: add updateNode/updateEdge API #3235
antvis/X6 pull request #3239
Opened 2023-02-14 14:43 UTC by lloydzhou

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-14 14:49 UTC, lloydzhou commented
close #3235

2023-02-15 06:35 UTC, lloydzhou commented
## 测试了一下：
1. updateNode(metadata)，如果metadata包含ports的时候，假如metadata.ports.items.length增加的时候画布能更新，metadata.ports.items.length减少的时候画布不能更新，必须手动调用一下cell.setProp('ports', metadata.ports)。
2. updateEdge(metadata)，如果包含labels的时候，和前面的表现一样不符合预期

还需要更完善的测试...

2023-02-15 08:28 UTC, lloydzhou commented
> ## 测试了一下：
> 1. updateNode(metadata)，如果metadata包含ports的时候，假如metadata.ports.items.length增加的时候画布能更新，metadata.ports.items.length减少的时候画布不能更新，必须手动调用一下cell.setProp('ports', metadata.ports)。
> 2. updateEdge(metadata)，如果包含labels的时候，和前面的表现一样不符合预期
> 
> 还需要更完善的测试...

问题似乎出在直接setProp(prop)调用的时候，走的流程和setProp(key, value)流程不一致导致的

2023-02-15 22:13 UTC, NewByVector requested changes

2023-02-15 22:13 UTC, NewByVector commented on packages/x6/src/model/model.ts
> +    const node = this.createEdge(metadata)
createNode?

2023-02-16 00:34 UTC, lloydzhou commented on packages/x6/src/model/model.ts
> +    const node = this.createEdge(metadata)
抱歉没有在x6项目这边直接写测试用例。
我只是在自己的另一个项目里面使用了类似的更新节点和边的代码进行测试。所以没注意到这个地方调用函数写错了。

2023-02-17 13:27 UTC, NewByVector approved these changes

2023-02-17 13:27 UTC, merged