[WIP]: 虚拟渲染修复
antvis/X6 pull request #3247
Opened 2023-02-16 08:44 UTC by struggleRoue

### Description

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-16 12:45 UTC, struggleRoue commented on packages/x6/src/renderer/scheduler.ts
> +    // const effectedEdges = this.getEffectedEdges(view)
@NewByVector 这块逻辑好像没用啊？帮忙确认一下？

2023-02-17 13:32 UTC, NewByVector requested changes

2023-02-17 13:32 UTC, NewByVector commented on packages/x6/src/view/edge.ts
> +    // const graph = this.graph
这个逻辑不能去掉的，如果 sourceView 没有创建的话，往下面走 render 逻辑，这次渲染其实是无效的。

2023-02-17 13:55 UTC, NewByVector requested changes

2023-02-17 13:55 UTC, NewByVector commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
刚才是举个例子，targetView 任然也是需要的。

2023-02-17 13:57 UTC, struggleRoue commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
targetView需要的话 那怎么能虚拟渲染还能显示边呢？
我试了一下demo 边能渲染

2023-02-21 07:41 UTC, NewByVector commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
所以这里要做一些处理，如果  targetView 不存在，而且开启虚拟渲染，需要渲染一个临时的边。
如果去掉上面代码，会对之前的渲染逻辑由影响，比如 targetView 没有的话，往下渲染而不是继续等待。

2023-02-21 08:19 UTC, struggleRoue commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
我有点get不到影响是什么

这个if的作用是 判断如果source或者target没有mounted，继续等待

而我们把这个if改成了不管source和target有没有mounted 都执行渲染

改的话我理解可以判断个virtual， 但是渲染临时的边我没get到

2023-02-21 08:33 UTC, struggleRoue commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
之前是什么场景必须要等targetView渲染出来 才能渲染边

2023-02-21 09:07 UTC, struggleRoue commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
难不成是为了解决V1版本， 大数据量的情况下边先出来 节点后出来的情况吗？

2023-02-22 02:36 UTC, closed without merging

2023-06-15 08:54 UTC, qiufeihong2018 commented on packages/x6/src/view/edge.ts
> +    // const targetView = this.targetView
请问这个问题修复了吗？

2023-06-15 13:38 UTC, qiufeihong2018 commented
@struggleRoue 这个分支解决了这个问题吗？如果解决了什么时候准备合入master？为什么这个问题closed了？