[wip]feat: data transfrom plugin init
antvis/X6 pull request #3258
Opened 2023-02-17 17:34 UTC by struggleRoue

### Description

新增一个数据转换插件
在toJSON的时候可以转换数据格式

**包名称待定**

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [✅] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-18 05:26 UTC, struggleRoue commented
@NewByVector 有时间可以看看还能怎么优化一下hhh  顺便起个名字？

2023-02-18 07:36 UTC, struggleRoue commented
注册插件后
transform实例提供toJSON和fromJSON能力，可以调用注册时的转换函数
graph原来的toJSON和fromJSON能力不变
Graph原型上挂载toJSONTransform和fromJSONTransform能力

2023-02-18 22:33 UTC, NewByVector commented
这个插件的功能定位应该包括：
1. 自定义数据转换
2. 支持 viso、bpmn、drawio、lucid 等数据格式
3. 这次树状结构数据

2023-02-19 09:39 UTC, lloydzhou commented
我不建议以插件的模式注册到Graph类上给开发者使用：

1. 想要让开发者能很好的写出一个toJSONTransform的函数，需要开发者对原来的toJSON之后的json结构有非常清晰的了解（但是现在文档对这个数据描述不是很清晰）。
2. 另外，toJSONTransform之后的数据，如果重新传递给fromJSONTransform，画布渲染之后应该是一致的。如果开放这两个方法给用户，肯定会有开发者无法做到这一点（转一次就转不回来了），这个时候开发者可能会把bug记到x6上面...
3. 我建议以独立的包纯粹导出一些转换函数的模式发布这个包，而不是强行注册到Graph类上面

2023-02-19 13:43 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:43 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:43 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:43 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:44 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:44 UTC, struggleRoue commented
> 这个插件的功能定位应该包括：
> 
> 1. 自定义数据转换
> 2. 支持 viso、bpmn、drawio、lucid 等数据格式
> 3. 这次树状结构数据
> 
> 刚开始功能不需要很完善，可以慢慢迭代，但是整体定位还是需要对齐一下。

主要功能我觉得还是自定义数据转换，
2-3中说到的有一点偏业务了， 当然也可以提供，不过这种业务耦合在仓库里是不是不太好，或者使用频率会很低

2023-02-19 13:45 UTC, struggleRoue commented
> 我不建议以插件的模式注册到Graph类上给开发者使用：
> 
> 1. 想要让开发者能很好的写出一个toJSONTransform的函数，需要开发者对原来的toJSON之后的json结构有非常清晰的了解（但是现在文档对这个数据描述不是很清晰）。
> 2. 另外，toJSONTransform之后的数据，如果重新传递给fromJSONTransform，画布渲染之后应该是一致的。如果开放这两个方法给用户，肯定会有开发者无法做到这一点（转一次就转不回来了），这个时候开发者可能会把bug记到x6上面...
> 3. 我建议以独立的包纯粹导出一些转换函数的模式发布这个包，而不是强行注册到Graph类上面

你说的当然是针对于业务层面去做了
JS库不应该耦合任何框架和业务

2023-02-19 14:15 UTC, struggleRoue commented
这个插件本意应该是以AOC的思想让用户去进行隐式的数据转换

用户不需要关心每个toJSON和fromJSON的位置，从切面去转换，减少理解成本

2023-02-20 03:11 UTC, lloydzhou commented on packages/x6-plugin-dataTransform/src/index.ts
> +    if (this.disabled) return this
感觉这里写得有问题：
1. disabled的时候，也应该需要走this.graph.fromJSON流程
2. 后面的if (fromJSONTransform) 这里和后面应该是if/else的关系


```
    const { fromJSONTransform } = this.options
    if (!this.disabled && fromJSONTransform) {
      this.graph.fromJSON(fromJSONTransform(data))
    } else {
      this.graph.fromJSON(data as Model.FromJSONData, options)
    }
    return this
```

2023-02-20 03:13 UTC, lloydzhou commented on packages/x6-plugin-dataTransform/src/index.ts
> +      this.graph.fromJSON(fromJSONTransform(data))
另外这里调用this.graph.fromJSON的时候，是否也应该把options传进去？

2023-02-20 03:18 UTC, struggleRoue commented on packages/x6-plugin-dataTransform/src/index.ts
> +      this.graph.fromJSON(fromJSONTransform(data))
是的，漏掉了

2023-02-20 03:19 UTC, struggleRoue commented on packages/x6-plugin-dataTransform/src/index.ts
> +    if (this.disabled) return this
是的

2023-02-20 08:25 UTC, struggleRoue commented
@NewByVector 我觉得可以先上一版本简版的，然后听听用户反馈

如果用户反馈强，需要转换函数，我们在帮忙增加一些转换函数？

2023-02-21 13:59 UTC, NewByVector commented
@struggleRoue 如果这个插件只是在 fromJSON 和 toJSON 之前做一层数据转换，我觉得这个就没有这个必要了。这个代码用户完全可以自己实现。

2023-02-21 14:00 UTC, NewByVector requested changes
如果这个插件只是在 fromJSON 和 toJSON 之前做一层数据转换，我觉得这个就没有这个必要了。这个代码用户完全可以自己实现。

2023-02-21 15:29 UTC, struggleRoue commented
我是这么理解的，当然这个插件不可能只包含这两个能力，只是具体的能力需要反馈？

而且我觉得如果我有面向切面的能力去做数据转换，我不会去手动处理，这会让代码维护成本增加

2023-06-17 13:54 UTC, closed without merging