fix(tool): 修复 node-editor 在 edge 上使用时，会出现 label 位置错乱和丢失问题
antvis/X6 pull request #3285
Opened 2023-02-23 05:34 UTC by lvyueyang

### 问题描述
修复 node-editor 在 edge 上使用时，会重复添加多个空 label，并且修改 label 时会导致 label 位置错乱和丢失的问题。  

### 重现链接
https://x6.antv.antgroup.com/examples/node/tool#editable  

### 重现步骤  
1. 点击 edge 添加 label 1，此时对应的 svg 节点下会出现两个 label 其中一个是空的。  
2. 修改 label 1，点击外部区域，确认修改后，label1 会消失。  

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-23 05:38 UTC, NewByVector requested changes
这样修改会导致一个问题，删除标签内文本后，鼠标离开，标签不消失。

2023-02-23 07:13 UTC, lvyueyang commented
> 这样修改会导致一个问题，删除标签内文本后，鼠标离开，标签不消失。

这个场景我漏掉了，确实会这样，我再改一下

2023-02-23 08:00 UTC, lvyueyang commented
我修改了 updateEditor 中的 setCellText 调用条件，仅针对 node 执行。
edge 的重影问题，使用 visibility 隐藏处理，修改完成后再移除 visibility。（因为 edge 的 lebel 被移除后再次修改会导致 distance 丢失）。

2023-02-27 07:21 UTC, NewByVector commented
我优化了一下，提了一个 https://github.com/antvis/X6/pull/3308

2023-02-27 09:00 UTC, closed without merging