feat: ✨ add `graph:scroll` event for `scroller` plugin
antvis/X6 pull request #3678
Opened 2023-06-14 13:39 UTC by 171h

feat: ✨ add `graph:scroll` event for `scroller` plugin

### Description

为 `x6-plugin-scroller`  插件提供了新的事件 `graph:scroll` 支持

### Motivation and Context

- 目前 `x6-plugin-scroller` 插件没有提供任何可用的事件， `graph` 在滚动的时候，可以通过 `graph:scroll` 事件执行一系列操作

### Types of changes
- [x] New feature (non-breaking change which adds functionality)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-06-17 14:41 UTC, NewByVector requested changes

2023-06-17 14:41 UTC, NewByVector commented on packages/x6-plugin-scroller/src/scroller.ts
> +    Dom.Event.on(this.container, 'scroll', () => {
如果是这样的话，在 X6 里面加的必要性不大呀，还不如直接在外面自己来定义这个事件。

2023-06-17 15:06 UTC, 171h commented on packages/x6-plugin-scroller/src/scroller.ts
> +    Dom.Event.on(this.container, 'scroll', () => {
在外面自己定义如何不方便获取这个dom，在内部加这个事件有现成的dom元素可用，内部加更好些吧。

2023-06-18 06:10 UTC, NewByVector commented on packages/x6-plugin-scroller/src/scroller.ts
> +    Dom.Event.on(this.container, 'scroll', () => {
scroll 方法是指设置滚动条位置吗，如果是的话，已经有了 [setScrollbarPosition](http://x6.antv.antgroup.com/tutorial/plugins/scroller#graphsetscrollbarpositionleft-number-top-number)。

2023-06-18 06:28 UTC, 171h commented on packages/x6-plugin-scroller/src/scroller.ts
> +    Dom.Event.on(this.container, 'scroll', () => {
> scroll 方法是指设置滚动条位置吗，如果是的话，已经有了 [setScrollbarPosition](http://x6.antv.antgroup.com/tutorial/plugins/scroller#graphsetscrollbarpositionleft-number-top-number)。
不是方法，是 scroll 事件，之前说错了， `scroll` 事件返回的值与 `getScrollbarPosition` 是一样的

2023-06-26 13:41 UTC, closed without merging