fix: fix size invalid on image node
antvis/X6 pull request #397
Opened 2020-12-11 13:53 UTC by NewByVector

### Description

解决 width 和 height 配置在 image 节点中不生效

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-12-11 14:31 UTC, bubkoo requested changes

2020-12-11 14:31 UTC, bubkoo commented on packages/x6/src/shape/standard/image.ts
> +    image: {
改错了吧，应该是下面这样。

```ts
export const Image = createShape(
  'image',
  {
    attrs: {
     image: {
        refWidth: '100%',
        refHeight: '100%',
      },
    },
    propHooks: getImageUrlHook(),
  },
  {
    selector: 'image',
  },
)
```

2020-12-12 01:30 UTC, NewByVector commented
大意了

2020-12-12 05:35 UTC, bubkoo approved these changes

2020-12-12 05:35 UTC, merged