fix: use `dom-align` to position dnd container (#3978)
antvis/X6 pull request #3979
Opened 2023-10-17 11:48 UTC by cyrilluce

### Description

fix #3978

### Motivation and Context

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-24 02:12 UTC, NewByVector requested changes

2023-10-24 02:12 UTC, NewByVector commented on packages/x6-plugin-dnd/src/index.ts
> +    // TODO 原组件目前没有使用这个返回值（代码注释掉了）
可以去掉，把这个注释删除吧。

2023-10-25 06:54 UTC, cyrilluce commented on packages/x6-plugin-dnd/src/index.ts
> +    // TODO 原组件目前没有使用这个返回值（代码注释掉了）
OK，因为ts约束，我先把 `originOffset` 属性删除了

2023-10-27 03:33 UTC, cyrilluce commented
ci失败了，看起来像是 runner 的问题？

2023-11-03 08:26 UTC, NewByVector approved these changes

2023-11-03 08:27 UTC, merged