fix: 🐛 fast switch menubar-item lead to multiple popup
antvis/X6 pull request #398
Opened 2020-12-12 01:35 UTC by zdc1111

问题： 快速切换item 会出现重复的 弹框
原因：isPrevMenuHiddening 函数为true 即上个菜单正在关闭时候 onMouseLeave 不会向 dom 写入deactive 关闭 弹出框函数     onMouseEnter 时候 执行销毁其它弹出框时候就会 调用不到
改动方案：onMouseLeave 去除 isPrevMenuHiddening 校验
优化： 销毁弹框事件不挂在dom 上面  减少dom上面事件 节省内存

2020-12-12 05:37 UTC, bubkoo commented
@NewByVector 测试一下这个修复，CR 一下代码。

2020-12-12 14:17 UTC, NewByVector requested changes

2020-12-12 14:17 UTC, NewByVector commented on packages/x6-react-components/src/menubar/item.tsx
> +const cacheDeactiveMap = new WeakMap()
这里可以用 WeakMap 防止对elem的强引用，以免造成内存泄露

2020-12-12 14:20 UTC, NewByVector approved these changes

2020-12-13 08:15 UTC, bubkoo approved these changes

2020-12-13 08:15 UTC, merged