feat: selection's pointerEvents support function type
antvis/X6 pull request #4067
Opened 2023-12-01 03:36 UTC by damnright

### "pointerEvents",one of the plugin "Selection"'s configuation,supporting function type
see [#4062](https://github.com/antvis/X6/issues/4062)

### "pointerEvents",one of the plugin "Selection"'s configuation,supporting function type
see [#4062](https://github.com/antvis/X6/issues/4062)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-09 02:28 UTC, NewByVector requested changes

2024-01-09 02:28 UTC, NewByVector commented on packages/x6-plugin-selection/src/selection.ts
> +      (showNodeSelectionBox !== true ||
不好意思，这么久才来 review 代码，注意到两个地方都有相似的判断，可以提取成一个函数。

2024-01-10 09:00 UTC, damnright commented on packages/x6-plugin-selection/src/selection.ts
> +      (showNodeSelectionBox !== true ||
okk

2024-01-24 06:17 UTC, NewByVector approved these changes

2024-01-24 06:17 UTC, merged