fix: optimize move performance while select multiple nodes
antvis/X6 pull request #4201
Opened 2024-02-14 10:06 UTC by xiawenqi

### Description
fix #1325

### Motivation and Context

当利用框选插件选中多个节点时，拖拽性能下降非常严重。主要原因是插件监听了节点的change事件，当节点拖拽时多次触发重新创建节点，大量的DOM操作导致页面卡顿。

解决方式为不再在节点change时触发重新创建选框，改为分别监听节点的position、angle、size变更事件，position时只需要变更选框位置，angle和size变更时重绘选框DOM。

对比选中200节点时的拖拽效果, 优化前：

https://github.com/antvis/X6/assets/3120383/20d5a101-91b0-48fd-bb1f-9628e960b722

优化后：

https://github.com/antvis/X6/assets/3120383/dfcfd18a-8519-4c0d-ab3e-699a6661c175

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-04-04 12:48 UTC, OpportunityLiu commented
egde 的事件忘了？

2024-04-28 12:42 UTC, NewByVector requested changes

2024-04-28 12:42 UTC, NewByVector commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
使用 cell:changed 确实会执行过于频繁。不过导致 box 修改的事件应该不止 angle/size 修改。

2025-08-12 01:54 UTC, hustcc commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
@xiawenqi @NewByVector @OpportunityLiu 这个 PR 还有后续吗？看 PR 的视频效果，提升是很明显的。

2025-08-12 03:31 UTC, OpportunityLiu commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
这么写 edge 不是没处理吗？

2025-08-12 12:05 UTC, hustcc commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
@OpportunityLiu 之前 cell 也不包含 edge 啊~

2025-08-12 13:29 UTC, OpportunityLiu commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
![动画](https://github.com/user-attachments/assets/765963d4-9d35-451d-9e22-596256119fd9)

确实哈，本来就有 bug，只在我的 fork 里修掉了

2025-08-12 13:48 UTC, OpportunityLiu commented on packages/x6-plugin-selection/src/selection.ts
> +    collection.on('node:change:angle', this.onCellChanged, this)
![动画](https://github.com/user-attachments/assets/636f8a1b-985f-4927-963c-c516b5974462)

edge 自己的事件不是在监听吗，只是不能通过框选选中而已啊

2025-09-26 08:44 UTC, GaoFuhong commented
https://github.com/antvis/X6/pull/4797
有兴趣可以看下这个提交哈。

2025-09-26 08:44 UTC, closed without merging