fix: x6 support ie 11
antvis/X6 pull request #585
Opened 2021-01-24 10:19 UTC by NewByVector

### Description

x6 support ie 11

### Motivation and Context

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-01-24 12:14 UTC, bubkoo requested changes

2021-01-24 12:14 UTC, bubkoo commented on packages/x6/src/util/object/inherit.ts
>      inherit(cls, base)
这里没看明白为什么要这么改？

之前的逻辑是“在实际运行时，不支持原生 class（原生class 在编译过程中没编译成兼容代码）时，才调用 `inherit` ”，现在改成了任何情况都调用 `inherit`，没太明白。

另外，兼容 IE11 的文件名 `"x6.esm.js"` 有点奇怪，esm 是 es module 的简称，用来表示 IE11 的文件不合适吧？

2021-01-24 12:38 UTC, NewByVector commented on packages/x6/src/util/object/inherit.ts
>      inherit(cls, base)
上面代码改动后是下面这样的，不能在运行时确定，不然打包成 es5 后，代码里面还是带有 class 关键字，IE11 语法报错。
```ts
export function createClass<T>(className: string, base: Function): T {
  // tslint:disable-next-line
  let cls
  if (isNativeClass) {
    cls = new Function('base',`return class ${className} extends base { }`)(base)
  } else {
    cls = new Function('base',`return function ${className}() { return base.apply(this, arguments) }`)(base)
    inherit(cls, base)
  }

  return cls as T
}
```
这个x6.esm.js 其实是 rollup 打包后的 es module，可以通过 import 语法导入的(与 tsc 的区别在于没有类型了)。

2021-01-25 05:34 UTC, bubkoo requested changes

2021-01-25 05:34 UTC, bubkoo commented on sites/x6-sites/docs/tutorial/faq/epilog.en.md
> +import { Graph } from '@antv/x6/dist/x6.esm.js'
import { Graph } from '@antv/x6/dist/x6'

2021-01-25 06:17 UTC, bubkoo approved these changes

2021-01-25 06:17 UTC, merged